version: 2.5.0.{build}

init:
  - choco install -y --force bzr
  - set PATH=C:\Program Files (x86)\Bazaar;%PATH%
  - bzr --version

clone_script:
  - bzr checkout --lightweight lp:openlp openlp

environment:
  PYTHON: C:\\Python34

install:
  # Install dependencies from pypi
  - %PYTHON%\python.exe -m pip install sqlalchemy alembic chardet beautifulsoup4 Mako nose mock pyodbc==3.0.10 psycopg2 pypiwin32 pyenchant
  # Install mysql dependency
  - %PYTHON%\python.exe -m pip install http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.4.zip#md5=3df394d89300db95163f17c843ef49df
  # Download and install lxml and pyicu (originally from http://www.lfd.uci.edu/~gohlke/pythonlibs/)
  - curl -L "https://www.dropbox.com/s/7dwwna459j6qvbp/lxml-3.6.4-cp34-cp34m-win32.whl?dl=1" -o lxml-3.6.4-cp34-cp34m-win32.whl
  - %PYTHON%\python.exe -m pip install lxml-3.6.4-cp34-cp34m-win32.whl
  - curl -L "https://www.dropbox.com/s/ib1yq4xq7o1dma7/PyICU-1.9.5-cp34-cp34m-win32.whl?dl=1" -o PyICU-1.9.5-cp34-cp34m-win32.whl
  - %PYTHON%\python.exe -m pip install PyICU-1.9.5-cp34-cp34m-win32.whl
  # Download and install PyQt5
  - curl -L -O http://downloads.sourceforge.net/project/pyqt/PyQt5/PyQt-5.5.1/PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe
  - PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe /S
  # Download and install Inno Setup - used for packaging
  - curl -L -O http://www.jrsoftware.org/download.php/is-unicode.exe
  - is-unicode.exe /VERYSILENT /SUPPRESSMSGBOXES /SP-
  # Download and unpack portable-bundle
  - curl -L  "https://www.dropbox.com/s/omr8mw9kamnml3l/portable-setup.7z?dl=1" -o portable-setup.7z
  - 7z x portable-setup.7z
  # Download and unpack mupdf
  - curl -O http://mupdf.com/downloads/archive/mupdf-1.9a-windows.zip
  - 7z x mupdf-1.9a-windows.zip
  - cp mupdf-1.9a-windows/mupdf.exe openlp/mupdf.exe
  # Download and unpack mediainfo
  - curl -O https://mediaarea.net/download/binary/mediainfo/0.7.90/MediaInfo_CLI_0.7.90_Windows_i386.zip
  - mkdir MediaInfo
  - cd MediaInfo
  - 7z x ../MediaInfo_CLI_0.7.90_Windows_i386.zip
  - cd..
  - cp MediaInfo\\MediaInfo.exe openlp\\MediaInfo.exe
  # Disabled portable installers - can't figure out how to make them silent
  # - curl -L -O http://downloads.sourceforge.net/project/portableapps/PortableApps.com%20Installer/PortableApps.comInstaller_3.4.4.paf.exe
  # - PortableApps.comInstaller_3.4.4.paf.exe /S
  # - curl -L -O http://downloads.sourceforge.net/project/portableapps/PortableApps.com%20Launcher/PortableApps.comLauncher_2.2.1.paf.exe
  # - PortableApps.comLauncher_2.2.1.paf.exe /S
  # - curl -L -O http://downloads.sourceforge.net/project/portableapps/NSIS%20Portable/NSISPortable_3.0_English.paf.exe
  # - NSISPortable_3.0_English.paf.exe /S


build: off

test_script:
  - cd openlp
  - %PYTHON%\\python.exe -m nose -v tests

after_test:
  # This is where we create a package using PyInstaller
  # First download and unpack PyInstaller
  - curl -L -O https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  - 7z x develop.zip
  # Then get the packaging repo
  - bzr checkout --lightweight lp:~tomasgroth/openlp/packaging-appveyor packaging
  - cd packaging
  - %PYTHON%\python.exe windows/windows-builder.py -v -u -t -c windows\\config.ini -b ..\\openlp

