version: OpenLP-win-ci-b{build}

clone_script:
  - curl -L https://bazaar.launchpad.net/BRANCHPATH/tarball -o sourcecode.tar.gz
  - 7z e sourcecode.tar.gz
  - 7z x sourcecode.tar
  - mv BRANCHPATH openlp-branch

environment:
  PYTHON: C:\\Python34

install:
  # Install dependencies from pypi
  - "%PYTHON%\\python.exe -m pip install sqlalchemy alembic appdirs chardet beautifulsoup4 lxml Mako mysql-connector-python nose mock pyodbc==4.0.8 psycopg2 pypiwin32==219 pyenchant pymediainfo websockets asyncio waitress six webob requests QtAwesome"
  # Download and install PyQt5
  - appveyor DownloadFile https://downloads.sourceforge.net/project/pyqt/PyQt5/PyQt-5.5.1/PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe
  - PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe /S
  # Download and unpack mupdf
  - appveyor DownloadFile https://mupdf.com/downloads/archive/mupdf-1.14.0-windows.zip
  - 7z x mupdf-1.14.0-windows.zip
  - cp mupdf-1.14.0-windows/mupdf.exe openlp-branch/mupdf.exe
  # Download and unpack mediainfo
  - appveyor DownloadFile https://mediaarea.net/download/binary/mediainfo/18.08.1/MediaInfo_CLI_18.08.1_Windows_i386.zip
  - mkdir MediaInfo
  - 7z x -oMediaInfo MediaInfo_CLI_18.08.1_Windows_i386.zip
  - cp MediaInfo\\MediaInfo.exe openlp-branch\\MediaInfo.exe

build: off

test_script:
  - cd openlp-branch
  # Run the tests
  - "%PYTHON%\\python.exe -m nose -v tests"
  # Go back to the user root folder
  - cd..

after_test:
  # This is where we create a package using PyInstaller
  # First get PyInstaller
  - appveyor DownloadFile  https://github.com/pyinstaller/pyinstaller/releases/download/v3.2/PyInstaller-3.2.zip
  - 7z x PyInstaller-3.2.zip
  # Install PyInstaller dependencies
  - "%PYTHON%\\python.exe -m pip install future pefile"
  # Download and install Inno Setup - used for packaging
  - appveyor DownloadFile http://www.jrsoftware.org/download.php/is-unicode.exe
  - is-unicode.exe /VERYSILENT /SUPPRESSMSGBOXES /SP-
  # Download and unpack portable-bundle
  - appveyor DownloadFile https://get.openlp.org/win-sdk/portable-setup.7z
  - 7z x portable-setup.7z
  # Disabled portable installers - can't figure out how to make them silent
  # - curl -L -O http://downloads.sourceforge.net/project/portableapps/PortableApps.com%20Installer/PortableApps.comInstaller_3.4.4.paf.exe
  # - PortableApps.comInstaller_3.4.4.paf.exe /S
  # - curl -L -O http://downloads.sourceforge.net/project/portableapps/PortableApps.com%20Launcher/PortableApps.comLauncher_2.2.1.paf.exe
  # - PortableApps.comLauncher_2.2.1.paf.exe /S
  # - curl -L -O http://downloads.sourceforge.net/project/portableapps/NSIS%20Portable/NSISPortable_3.0_English.paf.exe
  # - NSISPortable_3.0_English.paf.exe /S
  # Get the packaging code
  - appveyor DownloadFile http://bazaar.launchpad.net/~openlp-core/openlp/packaging/tarball -FileName packaging.tar.gz
  - 7z e packaging.tar.gz
  - 7z x packaging.tar
  - mv ~openlp-core/openlp/packaging packaging
  # If this is trunk we should also build the manual
  - ps: >-
      If (BUILD_DOCS) {
        &"$env:PYTHON\python.exe" -m pip install sphinx
        Invoke-WebRequest -Uri "http://bazaar.launchpad.net/~openlp-core/openlp/documentation/tarball" -OutFile documentation.tar.gz
        7z e documentation.tar.gz
        7z x documentation.tar
        mv ~openlp-core/openlp/documentation documentation
        cd packaging
        &"$env:PYTHON\python.exe" builders/windows-builder.py --skip-update -c windows/config-appveyor.ini -b ../openlp-branch -d ../documentation --portable --tag-override TAG
      } else {
        cd packaging
        &"$env:PYTHON\python.exe" builders/windows-builder.py --skip-update --skip-translations -c windows/config-appveyor.ini -b ../openlp-branch --portable --tag-override TAG
      }

artifacts:
  - path: openlp-branch\dist\*.exe
